### PR TITLE
956 fixing quickstart link

### PR DESCRIPTION
**Pull request by mzumbadoate**
fixes stormpath/stormpath-sdk-java#956

### CODE REVIEW

**Comment by jarias** [comment]
@mzumbadoate Looks like there are conflicts with the latest upstream, need to fix this, otherwise it looks good.

**Comment by jarias** [comment]
LGTM

**Comment by mzumbadoate** [comment]
@omgitstom @mrioan @dogeared can someone please merge this PR, I don't have access to stormpath.github.io

**Comment by lhazlewood** [comment]
@mzumbadoate can you please try to re-build to resolve the branch conflict?

**Comment by mzumbadoate** [comment]
@lhazlewood maybe because I don't have write access to  stormpath.github.io I don't see any conflict, I don't know what conflict are you talking about, can you copy maybe here the conflict message please?

**Comment by jarias** [comment]
@lhazlewood I think you got confused like I did the github message says it has a conflict but not a merge conflict just permission conflict cause we don't have write access to this repo.

Full Github message

```
This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.
```

**Comment by lhazlewood** [comment]
@jakubswiatczak fixed this before I had a chance to merge, so we can close this now.  Thanks!

**Pull request closed without merging**
