### PR TITLE
Fixes stormpath/stormpath-sdk-java#321

### PR DESCRIPTION
**Pull request by jarias**
Incorrect reference to a Spring functionality as a Stormpath one

Fixes stormpath/stormpath-sdk-java#321

### CODE REVIEW

**Comment by mraible** [comment]
Looks good to me. :+1:

**Comment by lhazlewood** [comment]
LGTM, please merge.

**Comment by lhazlewood** [comment]
ah, sorry, I need to.

**Comment by lhazlewood** [comment]
@dogeared can we just merge this?  Or is there anything else that needs to be done after that?

**Comment by dogeared** [comment]
@lhazlewood - we can merge.

**Pull request merged**
